### ISSUE TITLE
Register as an logged in user leads to error 403

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#147]
Here the user should be redirected to the main page

steps to reproduce
1. got to http://yawik.org/demo/de
2. Login 
3. call http://yawik.org/demo/de/auth/register

**Comment by mbo-s** [comment]
There are more pages that produce the same error, e.g.
http://yawik.org/demo/de/auth/forgot-password

**Comment by cbleek** [comment]
An authenticated user is currently denied to get the registration page because of:

https://github.com/cross-solution/YAWIK/blob/develop/module/Auth/config/module.config.php#L395

Because of this configuration an Exception is thrown. The exception handling is not implemented yet, because we don't know what to do. It probably should be configurable.

**Comment by mbo-s** [comment]
A similar problem existed with the register form, here the authenticated user will be redirected to the main page and that is common
https://github.com/cross-solution/YAWIK/blob/develop/module/Auth/src/Auth/Controller/IndexController.php#L66-L68
