### ISSUE TITLE
© 2013-2015 Cross Solution. All rights reserved.

### ISSUE THREAD

**Issue by utrenkner** [cross-solution/YAWIK#172]
This appears in the footer of a new YAWIK installation. The "All rights reserved" should be replaced by something that mentions the MIT license under which YAWIK is published to indicate that this is indeed free software.

**Comment by cbleek** [comment]
a hardcoded "© 2013-2015 Cross Solution" in the default layout is indeed confusing. 
We have the core options which allow to set contact data of an operator. I've replaced the hard coded stuff with these settings.

Regardless an individual layout should replace the default view script completly.

I haven't removed the "All rights reserved", because translations exists.
