### ISSUE TITLE
Upgrade Zend

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#217]
#192 was the reason, why we've fixed the version of zend_form etc.

As far as I know, after an upgrade, it was not possible to apply on a job opening.

Mathias sent me a couple of links, which should help to understand, how we want to replace the deprecated code.

https://github.com/cross-solution/YAWIK/blob/develop/module/Core/src/Core/EventManager/EventManager.php

https://github.com/cross-solution/YAWIK/blob/develop/module/Core/src/Core/EventManager/EventProviderInterface.php

https://github.com/cross-solution/YAWIK/blob/develop/module/Core/src/Core/Factory/EventManager/EventManagerAbstractFactory.php

Für die lazy loading listener wird der hier benutzt:

https://github.com/cross-solution/YAWIK/blob/develop/module/Core/src/Core/Listener/DeferredListenerAggregate.php

Example-Configurations:
https://github.com/cross-solution/YAWIK/blob/develop/module/Orders/config/module.config.php#L43

https://github.com/cross-solution/YAWIK/blob/develop/module/Jobs/config/module.config.php#L215

**Comment by TiSiE** [comment]
@fedys You might want to look at 
https://zendframework.github.io/zend-eventmanager/migration/removed/
https://zendframework.github.io/zend-eventmanager/migration/changed/

**Comment by fedys** [comment]
I did following steps:
replaced:
	"zendframework/zendframework": "2.*",
	"zendframework/zend-mvc": "2.6.*",
	"zendframework/zend-form": "2.6.*",
with:
	"zendframework/zendframework": "^2.5"
and run composer update zendframework/*

Because ServiceLocatorAwareInterface and ServiceManagerAwareInterface are deprecated I refactored all classes using these interfaces via constructor injection. I also fixed several bugs (non-existent Zend package methods call, etc.). I did also some code clean-ups. All tests pass now.

**Comment by fedys** [comment]
Finally, the zend-mvc 3.0 has been released. Unfortunately, it is not possible to upgrade to the zend-mvc 3.0 now because of dependencies in other packages (e.g.: doctrine-mongo-odm-module depends on zend-mvc 2.* etc.) We have to wait for authors of these packages to provide upgrades or make our own clones.
