### ISSUE TITLE
Applicant registered as new user with role 'recruiter'

### ISSUE THREAD

**Issue by cjriks** [cross-solution/YAWIK#224]
After saving a new application to one of our jobs online the applicant is registered as a new user with role 'recruiter', here the entry from the database:

```
{
    "_id" : ObjectId("575d95dc1f7859a12a2c48ef"),
    "login" : "xxxx.xxxxxxxx@t-online.de",
    "role" : "recruiter",
    "info" : {
        "email" : "xxxx.xxxxxxxx@t-online.de",
        "emailVerified" : true,
        "firstName" : "XXXXXX",
        "lastName" : "XXXXXXX",
        "image" : null
    },
    "credential" : "***************************************************",
    "profile" : {},
    "profiles" : {},
    "isDraft" : false,
    "status" : {
        "name" : "active",
        "order" : 50
    },
    "email" : "xxxxxx.xxxxxxxxx@t-online.de",
    "settings" : [ 
        {
            "_module" : "Core",
            "localization" : {},
            "_entity" : "Core\\Entity\\SettingsContainer"
        }
    ]
}
```

In the application I found attached rights:

```
....
"permissions" : {
        "type" : "Application",
        "view" : [ 
            "575d95dc1f7859a12a2c48ef", 
            ....
        ],
        "change" : [ 
            ....
        ],
        "assigned" : {
            "user:575d95dc1f7859a12a2c48ef" : {
                "view" : [ 
                    "575d95dc1f7859a12a2c48ef"
                ]
            },
....
```

Registration and login with social media are disabled, in auth.options.global.php:
```
$options = array(
       /*
        * default email address, which is used in FROM headers of system mails like "new registration",
        * "forgot password",..
        */
        'fromEmail' => 'tester@no-reply.com',

        /*
        * default name address, which is used in FROM headers of system mails like "new registration",
        * "forgot password",..
        */
        'fromName' => 'My Company',

        /*
        * Subject of your registration Mail
        */
        'mailSubjectRegistration' => 'Your registration at my Company',

        /*
         * enable social networks for login and registration. The names must match the keys used in 
         * in the 'hybridauth' section of you module.auth.global.php file
         */
         #'enableLogins' => ['linkedin','github','xing','google','facebook'],
         'enableLogins' => [],

        /*
         * if true, users are allowed to register.
         */
         'enableRegistration' => false,

        /*
         * if true, users can reset their password.
         */
         'enableResetPassword' => true,

    );

```

Why was this applicant inserted as a new user? What can this user see on the platform? This never happened on other applications before and not with a later one...

Code is current develop tree as at 2016-06-08

**Comment by TiSiE** [comment]
Is OneClickApply enabled for this job ad? Because that's the only place in the application process where eventually a user could be created in the database because of the usage of partially Auth module code.

There must be some data in the "profiles" key though, which is not the case ... puzzling!

As a recruiter, an user can see his own job as well as any job created for his company (or the company he is associated as an employee and he is given the rights). The recruiter can add a new organization (Login menu -> create organization) and can create new job offers. He can also invite users as employees to his own organizations.

He cannot see, access, or modify jobs or organizations NOT created by him (except the jobs for his own organization).

This behaviour to an application (creating users I mean) is very strange and needs some inspection!

**Comment by cjriks** [comment]
Hi,
sorry for confusions, it looks like as it was my own fault...
The code in auth.options.global.php was copied from my develop installation, assuming it is identical with the production one. But on our production server the option for registration was still on "true", because this file was excluded by .gitignore....
Sorry again, please close this issue.
