### ISSUE TITLE
Move an Applicant into the Talent Pool

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#233]
original feature Requests:

> 
>  - Bewerber, die eingeladen wurden und uns dann abgesagt haben müssen
>    momentan noch im Status "eingeladen" bleiben, da sie sonst eine automatische
>    Absage über Yawik erhalten
> - ein Abschalten dieser "Automatisierten" Mails wäre manchmal sinnvoll
> 
> "sollte man ausblenden können / oder in ein separates Archiv verschieben können
> am besten für jede Stellenaussschreibung ein separates Archiv"

**Comment by cbleek** [comment]
It should be possible to move an application into the talent-pool. The application should be removed from the applications collection and added to the cvs collection.

**Comment by fedys** [comment]
@cbleek Please provide me more details. I do not understand the German comment because of my poor German language :).

Should an application be hidden in the Application section and be visible in an extra subsection of the Section Talent-Pool (based on some Application's internal flag)?

Or an application should be hard-deleted and transformed into a new Cv entity (what data should be kept/transformed)?

**Comment by cbleek** [comment]
@fedys : the application should be hard-deleted and transformed into a new CV. 

But you're right. We should first make the CV able to take all the data of a resume. Therefore I've created #242 . Please first add the possibility to add attachments to a CV.

**Comment by fedys** [comment]
@cbleek  OK, I am going to implement it on Thursday.

**Comment by cbleek** [comment]
Everything was merged and is working as expected
