### ISSUE TITLE
Notice: Trying to get property of non-object in index.recruiter.ajax.phtml

### ISSUE THREAD

**Issue by fedys** [cross-solution/YAWIK#282]
If you are logged as an administrator you get the following notice: `Trying to get property of non-object in /data/www/clients/client1/web1/YAWIK/module/Applications/view/applications/manage/index.recruiter.ajax.phtml on line 170` on the [application page](https://yawik.org/demo/en/applications).

**Comment by TiSiE** [comment]
Because for administrators somehow the drafts (eg: isDraft: true) are shown. Drafts do not have a status yet.

Solutions:
* Don't show drafts in listing even for administrators   
  Which means modifying the PaginationQuery.
* Indicate that the application is still a draft   
  Which means adding a check in the view.

I tend to like the first solution better...

**Comment by fedys** [comment]
Maybe I would add a check in the listing plus add an additional filter called _draft_ with the following options: _Do not display (the default one)_, _Only_ and _All_

**Comment by TiSiE** [comment]
From the users' point of view, I would prefer combining this filter in the status select box, so one can select:

- all (with drafts)
- all (w/o drafts)
- drafts
- + other states

**Comment by fedys** [comment]
You are right, I did not realize that drafts have no states.

**Comment by TiSiE** [comment]
While it is technically possible to implement it the outlined way, there might be privacy issues.   
An application draft is created PRIOR to the user accepted (and read) the privacy agreement, which means using the data and displaying them to the admin/recruiters CAN be problematic.

@cbleek what do you think?
