### ISSUE TITLE
PNotify notification in the demo are broken

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#285]
is the problem located in the demo skin or in the core?

**Comment by TiSiE** [comment]
[module/Core/public/js/core.init.js](https://github.com/cross-solution/YAWIK/blob/badad1880ee29d147e8ee8d49f4d45f8197a51ff/module/Core/public/js/core.init.js#L35) uses the jquery function size(), which is deprecated since 1.8 and removed in jquery 3. Since our [composer.json](https://github.com/cross-solution/YAWIK/blob/badad1880ee29d147e8ee8d49f4d45f8197a51ff/composer.json#L42) requires the latest version, currently jquery 3 will be installed.
