### ISSUE TITLE
Move an application with attachments to talent pool does not work.

### ISSUE THREAD

**Issue by TiSiE** [cross-solution/YAWIK#296]
Trying to move an application with attachments to the talent pool results in exceptions stating that \Core\Entity\Collection does not have a ::getMapping() method or - even weirder - Doctrine expects a PersistentCollection but recievies an ArrayCollection.

**Comment by fedys** [comment]
I don't know if the following help you to solve it somehow, I found out commenting out [this line](https://github.com/cross-solution/YAWIK/blob/dee413c298933038a53a962ff52b996c3caa5a9f/module/Cv/src/Cv/Repository/Cv.php#L53) prevent the exception to be thrown.
I am still searching for the root cause.
