### ISSUE TITLE
[ZF3] bin/console does not work

### ISSUE THREAD

**Issue by TiSiE** [cross-solution/YAWIK#414]
Zend Framework 3 removed the Console component from its MVC component and moved it to its own component:
https://zendframework.github.io/zend-mvc-console/intro/

We need to integrate this module and make YAWIKs' console api working again.

----
In a second step we should consider following the suggestion made in the last paragraph of the above link:
Use zf-console as zend-mvc-console will be abondoned.

**Comment by TiSiE** [comment]
@kilip Please do this.

**Comment by kilip** [comment]
@TiSiE based on answer in this stackoverflow question:

https://stackoverflow.com/questions/38636186/how-to-create-zf3-console-application

I think we should start using `symfony console` component to handle yawik related console job, because I am more familiar in working with `symfony console` then `zf-console`. I want you to notice that `symfony console` is widely used in opensource project like `composer`, `doctrine`.

I have create this `symfony console` integration in [feature-zf3-console](https://github.com/kilip/YAWIK/tree/feature-zf3-console). And because doctrine is using `symfony console` too, I could easily import doctrine command into our yawik console application. I also create `app:generate:keywords` command to automaticaly generate keywords from all applications.

Here's a sample output:
![screenshot from 2017-09-19 14-47-39](https://user-images.githubusercontent.com/301065/30579127-e2a34da2-9d49-11e7-965a-110637d26b79.png)

**Comment by TiSiE** [comment]
**Our primary goal** is to make the yawik  console tools **working with zf3 ASAP**, which means we will use zend-mvc-console, as it does not require to change any code (because it is backward compatible with zf2)

For the long term migration (what I described as second step) I did not mean to dictate the usage of zf-console, that was just the one mentioned in the documentation I have linked to. 

But we should probably discuss this on the mailing list, in the forum or in another issue.

**Comment by kilip** [comment]
@TiSiE  my #413 pull request should fix this issue, I have integrated zend-mvc-console into yawik
