### ISSUE TITLE
update jQuery

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#454]
there is a Vulnerability in jquery. We're using jquery 2 because 

> module/Core/public/js/core.init.js uses the jquery function size(), which is deprecated since 1.8 and removed in jquery 3. Since our composer.json requires the latest version, currently jquery 3 will be installed.

https://github.com/cross-solution/YAWIK/issues/285

@kilip can you take a look?

**Comment by kilip** [comment]
Yes, start working on this issue now.

**Comment by kilip** [comment]
@cbleek @TiSiE 

In #455 pull request I remove `components/jquery` dependencies in composer configuration. Because `jquery` is loaded in [package.json](https://github.com/cross-solution/YAWIK/blob/970920208025278ea51a87498a83dc76fae4629a/package.json#L18), and exported with [install-assets.sh](https://github.com/cross-solution/YAWIK/blob/970920208025278ea51a87498a83dc76fae4629a/bin/install-assets.sh#L13) command. `jquery` now upgraded into `^3.0.0` version.

I also want to notice that this notification is tested in behat test such as this [login.feature](https://github.com/cross-solution/YAWIK/blob/970920208025278ea51a87498a83dc76fae4629a/features/account/login.feature#L16). In that test behat will verify that `You are now logged in` notification is showed.

**Comment by cbleek** [comment]
Thanks. The demo runs with jQuery3
