### ISSUE TITLE
A user with role recruiter can accept/reject every job

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#98]
Steps to reproduce
create a new account, manually change your role to recruiter 

open a job e.g. http://yawik.org/demo/en/jobs/view?id=537a23d56b10f8f67c8b4568
Take the id, here 537a23d56b10f8f67c8b4568
and call http://yawik.org/demo/en/jobs/approval?id=537a23d56b10f8f67c8b4568
then you can reject active jobs and accept every job.

If you are still logged in and call again the job url
http://yawik.org/demo/en/jobs/view?id=537a23d56b10f8f67c8b4568
you can still see the jobposting.
A guest gets an 404 error

**Comment by cbleek** [comment]
Commit 8fd55b1 was undone.

**Comment by cbleek** [comment]
You now need an "admin" role to approve a job opening. Currently you have to change your role via mongo cli to "admin"

Currently, the admin role inherits all rights of a recruiter. This will be changed. Because an "admin" must not be able to restrict rights of administrators. Thy e.g. must not see applications by default.
